# These substitutions allow the end user to override certain values
substitutions:
  name: "status-lamp"

esphome:
  name: "${name}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: esphome.status-lamp
    version: "1.12"

esp8266:
  board: esp01_1m

# To be able to get logs from the device via serial and api.
logger:

# API is a requirement of the dashboard import.
api:

# OTA is required for Over-the-Air updating
ota:

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://djiesr/HQLSTR-status-lamp/status-lamp-esp01.yaml@main

wifi:
  # Set up a wifi access point using the device name above
  ap:
    password: "12345678"

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal:

###########################################################

light:
  - platform: neopixelbus
    id: ledstrip1
    type: GRB
    variant: WS2811
    pin: GPIO03
    num_leds: 4
    name: "Status-Lamp"
    effects:
      - addressable_color_wipe:
          name: Color Wipe Effect With Custom Values
          colors:
            - red: 100%
              green: 100%
              blue: 100%
              num_leds: 3
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 1
          add_led_interval: 100ms
          reverse: false
  - platform: partition
    name: "Led 1"
    segments:
      # Use first 10 LEDs from the light with ID light1
      - id: ledstrip1
        from: 0
        to: 0
  - platform: partition
    name: "Led 2"
    segments:
      # Use first 10 LEDs from the light with ID light1
      - id: ledstrip1
        from: 1
        to: 1
  - platform: partition
    name: "Led 3"
    segments:
      # Use first 10 LEDs from the light with ID light1
      - id: ledstrip1
        from: 2
        to: 2
  - platform: partition
    name: "Led 4"
    segments:
      # Use first 10 LEDs from the light with ID light1
      - id: ledstrip1
        from: 3
        to: 3
        
